name: Update data
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  update:
    name: update data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
          lfs: true
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: run script
        run: |
          echo ::set-output name=results::$(python update/update.py)
        id: run_update_script
      - name: commit
        env:
          UPDATED: ${{ steps.run_update_script.outputs.results }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: steps.run_update_script.outputs.results != 'nada'
        run: |
          git config --global user.email "covid19-bot@example.com"
          git config --global user.name "covid19-bot"
          git add -A
          git status
          git commit -m "[ci] $UPDATED"
          git push -q "https://$GH_TOKEN@github.com/mauforonda/casos-covid-19-acumulado-por-municipios.git" master
